emoji_map = {
    "burger": "🍔",
    "hamburger": "🍔",
    "pizza": "🍕",
    "salad": "🥗",
    "soup": "🍲",
    "pasta": "🍝",
    "spaghetti": "🍝",
    "fish": "🐟",
    "fruit": "🍉",
    "cake": "🍰",
    "cookie": "🍪",
    "cupcake": "🧁",
    "donut": "🍩",
    "pancake": "🥞",
    "waffle": "🧇",
    "sandwich": "🥪",
    "hotdog": "🌭",
    "potato": "🥔",
    "sushi": "🍣",
    "chicken": "🍗",
    "ayam": "🍗",
    "rice": "🍚", 
    "nasi": "🍚",
}